version: "3"
services:
  server-app:
    build: ./framework-api
    image: framework-api
    ports:
      - "6060:6060"
    volumes:
      - ./framework-api/src/:/app
    networks:
      - intranet
  db:
    build: ./framework-database
    image: framework-database
    environment:
      - NEO4J_AUTH=neo4j/blabla
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - intranet
networks:
  intranet:


